modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/XiaoXianHW/EasyLAN"
authors="${mod_authors}"
description='''${mod_description}'''