modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/XiaoXianHW/EasyLAN/issues"
license="GNU General Public License v3"

[[mods]]
modId="easylan"
version="v1"
displayName="EasyLAN"
displayURL="https://github.com/XiaoXianHW/EasyLAN"
authors="XiaoXian"
description='''A Custom LAN Server Mod!:DDD'''
